# Generated by Django 5.0.7 on 2024-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('company_site', models.URLField(default='', max_length=255, null=True)),
                ('created_year', models.IntegerField(default=2024)),
                ('employee_count', models.CharField(choices=[('1-10', 'Від 1 до 10'), ('10-50', 'Від 10 до 50'), ('50-100', 'Від 50 до 100'), ('100-500', 'Від 100 до 500'), ('500+', 'Більше 500')], default='1-10', max_length=7)),
                ('main_image', models.ImageField(blank=True, default='', upload_to='companies/main_photo/%Y/%m/%d')),
                ('layer_image', models.ImageField(blank=True, default='', upload_to='companies/layer_photo/%Y/%m/%d')),
                ('facebook_link', models.URLField(blank=True, max_length=255)),
                ('instagram_link', models.URLField(blank=True, max_length=255)),
                ('linkedin_link', models.URLField(blank=True, max_length=255)),
                ('description', models.TextField(default='')),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyVacancies',
            fields=[
                ('vacancy_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vacancy_title', models.TextField(default='')),
                ('company_id', models.ManyToManyField(to='main.company')),
            ],
        ),
    ]
