# Generated by Django 5.0.7 on 2024-07-31 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=60)),
                ('city_image', models.ImageField(blank=True, default='', upload_to='cities/city')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=130)),
                ('slug', models.SlugField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='companyvacancies',
            name='city_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='companyvacancies',
            name='profession_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.profession'),
        ),
    ]
