# Generated by Django 5.0.7 on 2024-08-02 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_profession_companyvacancies_city_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.region'),
        ),
    ]
