# Generated by Django 5.0.7 on 2024-08-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_region_city_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.region'),
        ),
    ]
